# Generated by Django 4.0 on 2022-11-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='author name')),
                ('author_age', models.IntegerField(verbose_name='author age')),
            ],
            options={
                'verbose_name': 'author',
                'db_table': 'authortable',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200, verbose_name='city name')),
                ('country_name', models.CharField(max_length=200, verbose_name='country name')),
            ],
            options={
                'verbose_name': 'city',
                'db_table': 'citytable',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='book name')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='MyApi.author')),
            ],
            options={
                'verbose_name': 'book',
                'db_table': 'booktable',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='author_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='MyApi.city'),
        ),
    ]
