# Generated by Django 4.0 on 2022-11-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=200, verbose_name='singer name')),
            ],
            options={
                'verbose_name': 'singer',
                'db_table': 'singertable',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='song name')),
                ('song_duration', models.IntegerField()),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='MyApi.singer')),
            ],
            options={
                'verbose_name': 'song',
                'db_table': 'songtable',
            },
        ),
    ]
